;; font
;;(when (member "Menlo" (font-family-list))
;;  (set-face-attribute 'default nil :font "Menlo-13"))


;; (require 'cnfonts)
;; 让 cnfonts 随着 Emacs 自动生效。
;; (cnfonts-enable)
;; 让 spacemacs mode-line 中的 Unicode 图标正确显示。
;; (cnfonts-set-spacemacs-fallback-fonts)

;; (setq cnfonts-use-face-font-rescale t)



;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>

(set-face-attribute
 'default nil
 :font (font-spec :name "-APPL-Monaco-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 11.5))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-WQYF-WenQuanYi Micro Hei Mono-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 13.5)))


;; 会隐藏标题栏
;;(set-frame-parameter nil 'undecorated t)

(provide 'init-basic-interface)
