## '#', ,  ##
## ,   ##

##  ##

# (), : 
dir=/Users/user/Downloads
# dir=/Volumes/Downloads/Downloads/videos///
# , 0, 1.16, :16M
#disk-cache=32M
# , , :prealloc
# : none < falloc ? trunc < prealloc
# falloctrunc
# NTFSfalloc, EXT3/4trunc, MAC 
#file-allocation=none
# 
continue=true

##  ##

# , , :5
#max-concurrent-downloads=5
# , , :1
max-connection-per-server=5
# , , 1M -1024M, :20M
# size=10M, 20MiB ; 15MiB 
min-split-size=10M
# , , :5
split=6
# , , :0
#max-overall-download-limit=0
# , :0
#max-download-limit=0
# , , :0
#max-overall-upload-limit=0
# , :0
#max-upload-limit=0
# IPv6, :false
#disable-ipv6=true
# , :60
timeout=60
# , 0, :5
#max-tries=5
# , :0
#retry-wait=0

##  ##

# 
input-file=/Users/user/.aria2.session
# Aria2`/`
save-session=/Users/user/.aria2.session
# , 0, 1.16.1, :0
#save-session-interval=60

## RPC ##

# RPC, :false
enable-rpc=true
# , :false
rpc-allow-origin-all=true
# , :false
rpc-listen-all=true
# , :[epoll, kqueue, port, poll, select], 
#event-poll=select
# RPC, , :6800
#rpc-listen-port=6800
# RPC, v1.18.4,  --rpc-user  --rpc-passwd 
#rpc-secret=<TOKEN>
# RPC, ,  --rpc-secret 
#rpc-user=<USER>
# RPC, ,  --rpc-secret 
#rpc-passwd=<PASSWD>
#  RPC  SSL/TLS ,
#  RPC  https  wss 
#rpc-secure=true
#  RPC  SSL/TLS ,
#  PEM ï --rpc-private-key 
#rpc-certificate=/path/to/certificate.pem
#  RPC  SSL/TLS 
#rpc-private-key=/path/to/certificate.key

## BT/PT ##

# (.torrent), BT, :true
#follow-torrent=true
# BT, , :6881-6999
listen-port=51413
# , :55
#bt-max-peers=55
# DHT, PT, :true
enable-dht=false
# IPv6 DHT, PT
#enable-dht6=false
# DHT, :6881-6999
#dht-listen-port=6881-6999
# , PT, :false
#bt-enable-lpd=false
# , PT, :true
enable-peer-exchange=false
# , PT, :50K
#bt-request-peer-speed-limit=50K
# , PT
peer-id-prefix=-TR2770-
user-agent=Transmission/2.77
# , , 0, :1.0
seed-ratio=0
# , , :false
# .aria2
#force-save=false
# BT, :true
#bt-hash-check-seed=true
# BT, , :false
bt-seed-unverified=true
# (.torrent), :false
bt-save-metadata=true
