#!/bin/bash

# Let tmux and terminal emulators set TERM; provide only a minimal fallback.
if [[ -z ${TERM:-} || ${TERM:-} == "dumb" ]]; then
  if [[ -n ${TMUX:-} ]]; then
    export TERM="tmux-256color"
  elif [[ -n ${KITTY_PID:-} ]]; then
    export TERM="xterm-kitty"
  else
    export TERM="xterm-256color"
  fi
fi
