#!/bin/zsh

[[ -o interactive ]] || return 0

# plugin manager
# unplugged: https://github.com/mattmc3/zsh_unplugged
# -----------------------------------------------------------------------------

: ${ZPLUGINDIR:=$HOME/.zsh/plugins}

# clone a plugin, find an init.zsh, source it, and add it to fpath
function plugin-load() {
  local giturl="$1"
  local plugin_name=${${giturl##*/}%.git}
  local plugindir="${ZPLUGINDIR:-$HOME/.zsh/plugins}/$plugin_name"

  if [[ ! -d "$plugindir" ]]; then
    command git clone --depth 1 --recursive --shallow-submodules "$giturl" "$plugindir"
    if [[ $? -ne 0 ]]; then
      echo "plugin-load: git clone failed for: $giturl" >&2 && return 1
    fi
  fi

  if [[ ! -f "$plugindir/init.zsh" ]]; then
    local initfiles=(
      $plugindir/$plugin_name.plugin.zsh(N)
      $plugindir/$plugin_name.zsh(N)
      $plugindir/$plugin_name(N)
      $plugindir/$plugin_name.zsh-theme(N)
      $plugindir/*.plugin.zsh(N)
      $plugindir/*.zsh(N)
      $plugindir/*.zsh-theme(N)
      $plugindir/*.sh(N)
    )
    if [[ ${#initfiles[@]} -eq 0 ]]; then
      echo "plugin-load: no plugin init file found" >&2 && return 1
    fi
    command ln -s "${initfiles[1]}" "$plugindir/init.zsh"
  fi

  source "$plugindir/init.zsh"
  fpath+=$plugindir
  [[ -d "$plugindir/functions" ]] && fpath+=$plugindir/functions
}

function plugins-load() {
  local repo
  for repo in "$@"; do
    plugin-load "git@github.com:${repo}.git"
  done
}

function plugin-compile() {
  local plugindir="${ZPLUGINDIR:-$HOME/.zsh/plugins}"
  autoload -Uz zrecompile
  local f
  for f in $plugindir/**/*.zsh{,-theme}(N); do
    zrecompile -pq "$f"
  done
}

function plugin-update() {
  local plugindir="${ZPLUGINDIR:-$HOME/.zsh/plugins}"
  local d
  for d in $plugindir/*/.git(/); do
    echo "Updating ${d:h:t}..."
    command git -C "${d:h}" pull --ff-only --recurse-submodules --autostash
  done
}

# zsh-completions must be on fpath before compinit.
plugins-load \
  zsh-users/zsh-completions \
  le0me55i/zsh-extract


# options
# https://zsh.sourceforge.io/Doc/Release/Options.html
# -----------------------------------------------------------------------------
setopt PROMPT_SUBST
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_SILENT
setopt PUSHD_IGNORE_DUPS
setopt COMPLETE_IN_WORD
setopt AUTO_LIST
setopt AUTO_MENU
setopt INTERACTIVE_COMMENTS
# MENU_COMPLETE cycles on the first Tab; AUTO_MENU waits for the second.

# history
# SHARE_HISTORY already appends incrementally (do not also set INC_APPEND_HISTORY).
# https://zsh.sourceforge.io/Doc/Release/Options.html#History
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt SHARE_HISTORY
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE

autoload -Uz compinit && compinit
autoload -Uz add-zsh-hook vcs_info
add-zsh-hook precmd vcs_info

limit coredumpsize 0


# auto complete
# https://zsh.sourceforge.io/Doc/Release/Completion-System.html
# -----------------------------------------------------------------------------
zstyle ':completion:*' completer _complete _approximate
zstyle ':completion:*:approximate:*' max-errors 2
zstyle ':completion:*' verbose yes
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' select-prompt '%SSelect:  lines: %L  matches: %M  [%p]'
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*:*:default' force-list always

zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:descriptions' format $'\e[01;33m -- %d --\e[0m'
zstyle ':completion:*:messages' format $'\e[01;35m -- %d --\e[0m'
zstyle ':completion:*:warnings' format $'\e[01;31m -- No Matches Found --\e[0m'
zstyle ':completion:*:corrections' format $'\e[01;32m -- %d (errors: %e) --\e[0m'

zstyle ':completion:*' expand 'yes'
zstyle ':completion:*' squeeze-shlashes 'yes'

zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:*:*:*:processes' force-list always
zstyle ':completion:*:processes' command 'ps -au$USER'

# https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#Version-Control-Information
zstyle ':vcs_info:*' actionformats '%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
zstyle ':vcs_info:*' formats '%F{3}[%F{2}%b%F{3}]%f '
zstyle ':vcs_info:*' enable git


# prompt
# https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html
# -----------------------------------------------------------------------------
# ~/path [branch] >
PROMPT='%F{blue}%~ ${vcs_info_msg_0_}%(?.%B%F{blue}.%B%F{red})>%f%b '


# keymaps
# https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Keymaps
# -----------------------------------------------------------------------------
bindkey -e

bindkey '^[[Z' reverse-menu-complete

sudo-command-line() {
  [[ -z $BUFFER ]] && zle up-history
  [[ $BUFFER != sudo\ * ]] && BUFFER="sudo $BUFFER"
  zle end-of-line
}
zle -N sudo-command-line
bindkey '\e\e' sudo-command-line

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# prefix history search: Up/Down (CSI and SS3) and emacs C-p/C-n
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^P' up-line-or-beginning-search
bindkey '^N' down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search
bindkey '^[OA' up-line-or-beginning-search
bindkey '^[OB' down-line-or-beginning-search

# zsh-autosuggestions wraps ZLE widgets; load after bindkey.
plugins-load zsh-users/zsh-autosuggestions
