#--------------------------------------------------------------------------
#  

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
#--------------------------------------------------------------------------
# 
# bind-key == bind
# unbind-key == unbind
# bind -r 
# bind -n ïprefix
#--------------------------------------------------------------------------
# 
set-option -g prefix M-b

# escape 
set -sg escape-time 0

# vi
set-window-option -g mode-keys vi

# vi 
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 
bind -r H resize-pane -L 10
# 
bind -r L resize-pane -R 10
# 
bind -r K resize-pane -U 5
#     
bind -r J resize-pane -D 5

# Vi
setw -g mode-keys vi

# 
bind-key ` last-window

bind Escape copy-mode

unbind p
bind p pasteb

bind -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel 'yank > #{pane_tty}'

# https://robots.thoughtbot.com/how-to-copy-and-paste-with-tmux-on-mac-os-x
# MacOS: brew install reattach-to-user-namespace
if-shell "uname | grep -q Darwin" "bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'"

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# prefix + r 
bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind-key -n S-Up set-option -g status
bind-key -n S-Down set-option -g status
bind-key -n S-Left previous-window
bind-key -n S-Right next-window

bind-key R run-shell "tmux-reset"


#--------------------------------------------------------------------------
# 

# 
set -wg allow-rename off                                                            
set -wg automatic-rename off

# 
set -g mouse on

# zsh
set-option -g default-shell /bin/zsh

# 
set -g default-terminal "tmux-256color"

# Ms modifies OSC 52 clipboard handling to work with mosh, see
# https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b
set -ag terminal-overrides "vte*:XT:Ms=\\E]52;c;%p2%s\\7,xterm*:XT:Ms=\\E]52;c;%p2%s\\7:RGB"

# enable OSC 52 clipboard
# https://medium.freecodecamp.org/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b
set -g set-clipboard on

set -g focus-events on

run '~/.tmux/plugins/tpm/tpm'

set -g set-titles on
# set-option -g set-titles-string '#{pane_current_path} | #{pane_title}'
set-option -g set-titles-string '#{pane_title}'

set -g status-interval 5
set -g renumber-windows on

set -g status-position bottom
set -g xterm-keys on
set -g status-style fg="#666666",bg=default
setw -g window-status-style fg="#666666",bg=default,default
setw -g window-status-current-style fg=red,bg=default
set -g message-style fg=white,bg=black,bright
set -g status-left " "
set -g status-justify left
setw -g window-status-format         ' #I. #W '
setw -g window-status-current-format ' #(echo "#{pane_current_command}") '
set -g status-right " #[fg=#666666] %m-%d %H:%M "
set -g pane-border-style fg="#222425"
set -g pane-active-border-style fg=red,bg=default
