(let ((gc-cons-threshold most-positive-fixnum)
      (file-name-handler-alist nil))

  (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file)
    (load custom-file))

  (require 'init-basic)
  (require 'init-basic-interface)
  (require 'init-elpa)
  (require 'init-doom-theme)
  (require 'init-doom-modeline)
  (require 'init-evil)
  (require 'init-org-mode)
  (require 'init-company)
  (require 'init-git)
  (require 'init-keymaps)
  (require 'init-lang-rust)
  (require 'init-lang-go)
  (require 'init-lang-dart))
