require 'plugins.vim-rooter'
require 'plugins.indentline'
require 'plugins.nerdtree'
require 'plugins.tagbar'
require 'plugins.fzf'
require 'plugins.vim-gitgutter'
require 'plugins.nerdcommenter'
require 'plugins.deoplete'
require 'plugins.editorconfig-vim'

require 'lsp.base'
require 'lsp.servers'

require 'actions'
require 'keymapping'
-- require 'autocmd'
