#--------------------------------------------------------------------------
#  

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'arcticicestudio/nord-tmux'
#--------------------------------------------------------------------------
# 
# bind-key == bind
# unbind-key == unbind
# bind -r 
# bind -n ïprefix
#--------------------------------------------------------------------------
# 
 
# vi
set-window-option -g mode-keys vi

# vi 
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 
bind -r H resize-pane -L 10
# 
bind -r L resize-pane -R 10
# 
bind -r K resize-pane -U 5
#     
bind -r J resize-pane -D 5

# 
bind-key ` last-window

bind Escape copy-mode

# escape 
set -sg escape-time 0

bind -T copy-mode-vi 'v' send -X begin-selection


# https://robots.thoughtbot.com/how-to-copy-and-paste-with-tmux-on-mac-os-x
# MacOS: brew install reattach-to-user-namespace
bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'


unbind p
bind p pasteb

# Vi
setw -g mode-keys vi

# key bindings for horizontal and vertical panes
# |ï
#unbind %
bind | split-window -h -c "#{pane_current_path}"

# -ï
# unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# prefix + r 
bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind-key -n S-Up set-option -g status
bind-key -n S-Down set-option -g status
bind-key -n S-Left previous-window
bind-key -n S-Right next-window

bind-key R run-shell "tmux-rest"

#--------------------------------------------------------------------------
# 


#--------------------------------------------------------------------------
# 

# 
set -wg allow-rename off                                                            
set -wg automatic-rename off

# 
set -g mouse on

# zsh
set-option -g default-shell /bin/zsh

# 
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g set-titles on
# set-option -g set-titles-string '#{pane_current_path} | #{pane_title}'
set-option -g set-titles-string '#{pane_title}'

set -g status-position bottom
set -g xterm-keys on
set -g status-style fg="#666666",bg=default
setw -g window-status-style fg="#666666",bg=default,default
setw -g window-status-current-style fg=red,bg=default
set -g message-style fg=white,bg=black,bright
set -g status-left " "
set -g status-justify left
setw -g window-status-format         ' #I. #W '
setw -g window-status-current-format ' #(echo "#{pane_current_command}") '
set -g status-right " #[fg=#666666] %m-%d %H:%M "
set -g pane-border-style fg="#222425"
set -g pane-active-border-style fg=red,bg=default
